version: '3'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ctf
      MYSQL_USER: ctfuser
      MYSQL_PASSWORD: ctfpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
